### ISSUE TITLE
No Member Role ID's

### ISSUE THREAD

**Issue by ozdeadmeat** [Markoudstaal/node-red-contrib-discord-advanced#1]
The **_msg.member._roles_** has been removed and replaced with **_msg.memberRoleNames_**. The names are useless for sustainable permission verification due to the ability to easily change the role names. A memberRoleID or similar data element needs to be available.

**Comment by Markoudstaal** [comment]
Fixed in c727a5a5ad720efc27532c7b936bbaa159dffa05.
