### ISSUE TITLE
"Error: Expected token to be set for this request, but none was present"

### ISSUE THREAD

**Issue by N0NameN0** [Markoudstaal/node-red-contrib-discord-advanced#100]
did i miss something ??

![image](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/assets/1048113/32630a3e-b365-4bea-93db-21bd6462924d)

for information, no docker here, native debian, nodejs 20, nodered 3.1.0, node-red-contrib-discord-advanced 3.5.0

**Comment by moseisleydk** [comment]
I get the same error now.

**Comment by javis86** [comment]
Could you export the flow and paste it here?
Thanks

**Comment by N0NameN0** [comment]
> Could you export the flow and paste it here? Thanks

`[
    {
        "id": "505e87400a348b67",
        "type": "tab",
        "label": "Demo Discord",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "4932896908125e8d",
        "type": "debug",
        "z": "505e87400a348b67",
        "name": "debug 13",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 720,
        "y": 180,
        "wires": []
    },
    {
        "id": "1c4fc90e7eecbda7",
        "type": "discordMessage",
        "z": "505e87400a348b67",
        "name": "",
        "channelIdFilter": "",
        "token": "",
        "x": 500,
        "y": 180,
        "wires": [
            [
                "4932896908125e8d"
            ]
        ]
    },
    {
        "id": "4e618cd3b95838a5",
        "type": "discordMessageManager",
        "z": "505e87400a348b67",
        "name": "",
        "channel": "",
        "token": "",
        "x": 530,
        "y": 280,
        "wires": [
            [
                "4932896908125e8d"
            ]
        ]
    },
    {
        "id": "c814a079703e49c4",
        "type": "inject",
        "z": "505e87400a348b67",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "channel",
                "v": "1156714157115183236",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "aze",
        "payloadType": "str",
        "x": 270,
        "y": 280,
        "wires": [
            [
                "4e618cd3b95838a5"
            ]
        ]
    }
]`

**Comment by javis86** [comment]
have all discord nodes bot configuration selected?
![image](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/assets/5216084/5dd717e9-b82d-4630-b51e-4440893998b2)

**Comment by N0NameN0** [comment]
> have all discord nodes bot configuration selected?

yes both.

**Comment by N0NameN0** [comment]
i just edited the discordmessagemanager node then revalidate it. i now have another message : 
![image](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/assets/1048113/7af758d4-651e-490e-b0c1-b273b9bb3c46)

**Comment by javis86** [comment]
![image](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/assets/5216084/78e5c1c8-7130-4430-b0da-9055992f928f)
On discord developer portal

**Comment by N0NameN0** [comment]
it was. I had to delete the node, recreate the node, and all is now ok. Very strange that exact same configured nodes acted differently. Thx anyway. i close the issue.

**Comment by josalesmedeiros** [comment]
I get this error from time to time. Recreating the configuration node or restarting the Node-RED fixes it, but after a few weeks (or months), the error comes back.
