### ISSUE TITLE
Node does not work with docker nodered/node-red

### ISSUE THREAD

**Issue by moafrancky** [Markoudstaal/node-red-contrib-discord-advanced#11]
Hi,

I tried to install your node in my nodered/node-red docker but it failed with this error "notsup Unsupported engine for node-red-contrib-discord-advanced@3.0.3: wanted: {"node":">=16.6.0"} (current: {"node":"14.18.1","npm":"6.14.15"})".

It seems that there are only 2 versions of node-red docker available. One with node v12 and one with node v14, nothing with node v16.

What could I do ?

Many thanks,
Kind regards.

**Comment by Slyke** [comment]
Just ran into this issue too. Maybe we can get a node v16.6 version docker image of nodered? It does say it's supported: https://nodered.org/docs/faq/node-versions

**Comment by epleypa** [comment]
@Slyke @moafrancky you can actually pull node v16 by targeting the nodered/node-red:latest-16 tag https://hub.docker.com/r/nodered/node-red/tags
