### ISSUE TITLE
Support Scheduled Events

### ISSUE THREAD

**Issue by Wyrrrd** [Markoudstaal/node-red-contrib-discord-advanced#110]
Hi,

I'd like to create a recurring event programmatically on the prelast friday every month, which is not supported by Discord itself.

Is it possible to add support for the GuildScheduledEvent class and its methods?

**Comment by JuliaSoriaSmith** [comment]
Hey, this was added in the latest PR [Added new nodes: Guild Manager, Event Manager, and message search functionality](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/pull/112). You can create events, see all events, delete events. Most of the explanation is within the actual node-red interface on how to use the new node.

This issue should now be closed

**Comment by javis86** [comment]
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/releases/tag/v.3.6.0
