### ISSUE TITLE
Support for registering and unregistering app commands

### ISSUE THREAD

**Issue by JuliaSoriaSmith** [Markoudstaal/node-red-contrib-discord-advanced#116]
Currently registering commands as per discordJS is built upon this:

const rest = new REST().setToken(token);

// and deploy your commands!
(async () => {
	try {
		console.log(`Started refreshing ${commands.length} application (/) commands.`);

		// The put method is used to fully refresh all commands in the guild with the current set
		const data = await rest.put(
			Routes.applicationGuildCommands(clientId, guildId),
			{ body: commands },
		);

		console.log(`Successfully reloaded ${data.length} application (/) commands.`);
	} catch (error) {
		// And of course, make sure you catch and log any errors!
		console.error(error);
	}
})();

This requires knowing the token. 

Deleting the commands uses:

// for guild-based commands
rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: [] })
	.then(() => console.log('Successfully deleted all guild commands.'))
	.catch(console.error);

// for global commands
rest.put(Routes.applicationCommands(clientId), { body: [] })
	.then(() => console.log('Successfully deleted all application commands.'))
	.catch(console.error);

This should be placed into a node

**Comment by javis86** [comment]
#117 I think we can use json, with some modifications of the node.
I'll be working in an approach for this.
The main issue with the current code and json commands is that we need to implement POST for new commands

**Comment by javis86** [comment]
#118 Here some changes that i need some feedback

**Comment by javis86** [comment]
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/releases/tag/v.3.6.0
