### ISSUE TITLE
Can't bulk set slash commands. 

### ISSUE THREAD

**Issue by Mantic** [Markoudstaal/node-red-contrib-discord-advanced#123]
I'm trying to bulk-set some slash commands and am hitting an error I can't figure out. It seems that my data is either being transformed or not set correctly. It works when I set one command, but not multiple.

```DiscordAPIError[50035]: Invalid Form Body 0[DICT_TYPE_CONVERT]: Only dictionaries may be used in a DictType```

here's my node that feeds into a `discordCommandManager` node.  
```
const commands = [
   {name:"ping", description:"Test Ping.", type:1},
   {name:'anotherping', description: "Some other command", type:1}
]

msg.commands = commands;
msg.action = "set";

return msg;
```

I've looked over the discord.js documentation and the source code of this node-red module, and everything seems to be in order.... but I just can't figure out what's going on.

**Comment by javis86** [comment]
This node uses discord api v10 POST endpoint to create commands. By definition you can only send 1 command at each time.
One solution to this could be use another node to iterate over the array of commands and to send it to the discordCommandManager

https://discord.com/developers/docs/interactions/application-commands#making-a-global-command
