### ISSUE TITLE
Cannot read properties of undefined (reading 'FLAGS')

### ISSUE THREAD

**Issue by Saam51** [Markoudstaal/node-red-contrib-discord-advanced#14]
Hi,
I just installed "node-red-contrib-discord-advanced" package on Node-Red (v2.1.4) and when i configure token for Discord i have this message : TypeError: Cannot read properties of undefined (reading 'FLAGS')
And in Node Red node i have message too : 
![image](https://user-images.githubusercontent.com/55413649/144638212-2c58eb49-bb3b-409e-865c-5e73906a8670.png)

And I already updated the token

I missed something?

**Comment by Markoudstaal** [comment]
Hi!

The error suggests DiscordJS wasn't installed on your machine.
Can you uninstall the node-red-contrib-discord-advanced through the palette manager, restart node-red and then re-install? See if that fixes it.

**Comment by Saam51** [comment]
Thank for reply.

Unfortunately I have the same issue.

**Comment by Saam51** [comment]
Thank you for your reply.

I re-installed the package and it's works! But we must reboot after the re-install.

Than you for your help!

**Comment by Markoudstaal** [comment]
Good! No problem :)
