### ISSUE TITLE
listen message "reply to messages"

### ISSUE THREAD

**Issue by MrThiemann** [Markoudstaal/node-red-contrib-discord-advanced#15]
Hey,

is it possible to only intercept the messages when someone replies to a message?
Example: User "a" sends instructions.
User "B" wants to say thank you and replies to the message from user "a" with "thx" ....
And this is exactly the message I want to intercept in order to be able to continue working with my bot. But much more!
i don't just want to see that user B writes "thx", but rather that it is "a response to the message from user a".

do you understand how i mean?

**Comment by juanhaywood** [comment]
It's possible with discord.js api: message.type=19 (reference: [types](https://discord.com/developers/docs/resources/channel#message-object-message-types))

But not sure if it aligns with what @Markoudstaal envisions for this NR add-on.

**Comment by Markoudstaal** [comment]
As juan states you can check if the type is a reply with message.type, which is available under msg.data.type in this node. Additionally dcef5d7 now give you the reference object, available under msg.data.reference. This object will contain the orginal messageID of the message that was replied to.
