### ISSUE TITLE
Attachment data

### ISSUE THREAD

**Issue by KiloVoltAmper** [Markoudstaal/node-red-contrib-discord-advanced#19]
The msg.data.atatchment property contains the attachment ID.
The msg.data property contains the channel ID. 
The msg.data.attachment  it doen't contain the file name.
Without the file name I can not build up the
cdn.discordapp.com/attachments/_CHANNELID_/_ATTACHMENTID_/**FILENAME**
link.

![image](https://user-images.githubusercontent.com/8103888/154490790-dfc483ea-b842-443d-8ba3-b986cbd0f990.png)

**Comment by javis86** [comment]
![image](https://user-images.githubusercontent.com/5216084/164709744-4ab74646-462c-4d58-b879-bb3cad745bc9.png)
