### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by mateusrovedaa** [Markoudstaal/node-red-contrib-discord-advanced#24]
When I use the interaction node to listen a button interaction, an error is being returned:

```
[red] Uncaught Exception:
[error] TypeError: Do not know how to serialize a BigInt
at stringify (<anonymous>)
at Object.stringify (/data/node_modules/flatted/cjs/index.js:76:17)
at Client.<anonymous> (/data/node_modules/node-red-contrib-discord-advanced/discord/discordInteraction.js:64:49)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

![image](https://user-images.githubusercontent.com/22747307/166697239-980df84f-71d1-44d1-8a25-8e19564d5944.png)

The flow I'm trying to use is the same as the example provided here on the Wiki, both the one that sends the message and creates with the buttons and the one that listens for an interaction.

I think this problem happens with commands too.

**Comment by javis86** [comment]
I'm facing how to resolve this because with my actual environment of node-red interactionObject serialize ok.
But testing outside i got this error.
A quickest way is adding 
```js
BigInt.prototype.toJSON = function () {
    return this.toString()
}
```
at the top of lib/discordBotManager
