### ISSUE TITLE
Can't install this node with a "standard" setup for pi (Node v14 is installed)

### ISSUE THREAD

**Issue by vico93** [Markoudstaal/node-red-contrib-discord-advanced#31]
I've installed Node-RED using the bash script provided [by the official site](https://nodered.org/docs/getting-started/raspberrypi), but this installs node v14 (in the docs still says v12), and nothing other version.

But when i tried to install this node using the Web UI it failed and the logs said it needs node v16. I'm afraid to update manually node to v16 and break something (i'm an expert in braking things already stable in my Pi). If the official script requires specifically v14 (maybe due some quirk in Pi 3b+, i dont know).

Is there any option left for me?

**Comment by javis86** [comment]
I open the raw for the script and there is a option in it for installation of node-red with node js 16 (https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

![image](https://user-images.githubusercontent.com/5216084/170577043-42b13d37-8f4d-4241-b0f7-9696eb2ba60a.png)

**Comment by javis86** [comment]
![image](https://user-images.githubusercontent.com/5216084/170577596-03d30adf-6d97-4988-b49b-693d98d4fb54.png)
This is the reason beacuse you have node 14
