### ISSUE TITLE
discordMessage: Payload empty

### ISSUE THREAD

**Issue by skythe83** [Markoudstaal/node-red-contrib-discord-advanced#53]
Hi community, 
it seems I'm the only person having this issue, but I'm posting this as a last resort, before reinstalling all of Raspbian.

### **Hard- & Software:**
Device: Raspberry PI 1 B+
Kernel: Linux pi 5.15.56+ #1575 Fri Jul 22 20:26:40 BST 2022 armv6l GNU/Linux
OS: Raspbian bullseye
Node-RED version: v3.0.2
Node.js  version: v16.17.0

### **The issue:** 
regardless of what I do, both msg.payload and msg.data.content from discordMessage module remain empty. Every other value including author name+id, message id (msg.data.id) are filled. The discordSendMessage is also behaving weirdly, as it complains about msg.channel not being set, even though it's set in the module itself. So I had to put another module in front, which sets the msg.channel value.

### **What I did before it stopped working:** 
I upgraded node-red from some early version 1.7 or similar to v3.0.2. This immediately broke node-red, as I still had a very old node.js version installed (presumably 10.x, whereas new node-red requires >12), so I compiled and installed LTS version v16.17.0, as no armv6 binaries were available. 

### **What I tried, in order to fix it:**
- Ran npm update, including audit force fix.
- Uninstalled node-red, deleted .node-red/node_modules, then installed node-red and needed modules again.
- Tried, but failed compiling the latest node.js 18. Currently still compiling with modified CXXFLAGS.
- Built a very simple flow, discordMessage connected to a debug node. Looked at the output.

### **Other notes:**
The issue happens in both node-red-contrib-discord and -advanced.
All other modules that I'm using, including mqtt, e-mail, http in/out and sqlite are working just fine.

What I'd like to do (but lack the skills): I'd like to create a tiny discord.js client which emulates the behavior of discordMessage and outputs whatever users type to console.log. I fail at getting the example on the discord.js page running though. This could help me in tracking the issue.

Any help would be most appreciated.
Thanks!
Robert

**Comment by javis86** [comment]
Did you enable Message Content Intent?
![image](https://user-images.githubusercontent.com/5216084/188678888-e726b451-5576-4284-98fb-1f6cb61f5395.png)
You can join us on discord if you want to.
Javier

**Comment by skythe83** [comment]
Thanks Javier for the quick reply.
I'll try that although my bot is really just my own one server with 3 or 4 channels. It's doing smart home stuff for me.

**Comment by skythe83** [comment]
> Did you enable Message Content Intent? ![image](https://user-images.githubusercontent.com/5216084/188678888-e726b451-5576-4284-98fb-1f6cb61f5395.png) You can join us on discord if you want to. Javier

This + re-deploying all nodes has solved the issue. Thanks a lot!
