### ISSUE TITLE
How to attach image from buffer into an embed?

### ISSUE THREAD

**Issue by Slyke** [Markoudstaal/node-red-contrib-discord-advanced#57]
I'm trying the following code:

```
const nodeFetch = context.global.get('nodeFetch');
const url = 'http://some/url/with/a.jpg';

const imageRequest = await nodeFetch(url, { encoding: null });
const imageBuffer = await Buffer.from(await imageRequest.arrayBuffer());

msg.payload = 'the message';
msg.embeds = {
    "description": 'description',
    "content": 'content',
    "title": 'title',
    files:[{
        "file": imageBuffer,
        "filename": "test.jpg"
    }]
};

return msg;
```

But I only get this:
![image](https://user-images.githubusercontent.com/6442613/190946534-180bba18-d4d3-4eef-8b56-66ff04e053e3.png)

I can see that the buffer is being filled correctly:
![image](https://user-images.githubusercontent.com/6442613/190946692-9bddaf10-4420-4d6f-9692-2ee2bff34b3f.png)

I have also manually encoded an image and dumped the base64 encoded stream like such:
```
  "file": Buffer.from('LONG BASE 64 TEXT HERE', 'base64'),
```

I read through this documentation:
https://v13.discordjs.guide/popular-topics/embeds.html#using-an-embed-object
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/wiki/discordMessageManager

But not sure why it's not working.

**Comment by javis86** [comment]
> msg.attachments    String        A location to an attachment. Can be online by URL or in the local filesystem.
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/wiki/discordMessageManager

First, you need to save your buffer in a file, and then put the fullpath in the attachments array

**Comment by Slyke** [comment]
Ohhh, it doesn't allow for buffers like in DiscordJS? Can I just dump to `/tmp`, attach to message, and then delete the original file in the temp directory?

**Comment by javis86** [comment]
Ohh, I only follow the node documentation, but I never touch this part of the code.
Following the discordjs docs, you can pass the buffer but i don't know why it's not working
![image](https://user-images.githubusercontent.com/5216084/191363232-4f321acd-a25b-44ee-b32e-7791c4dfe99c.png)

**Comment by javis86** [comment]
Ohhh, maybe you need put the Buffer in the "msg.attachments", not inside embeds object. And then, reference it on the image field in the embed

![image](https://user-images.githubusercontent.com/5216084/191365275-6d643d0e-6a97-4e88-bb8f-690ed51c51f9.png)

**Comment by Slyke** [comment]
Hmmm, how do I attach it to `msg.attachments` and then refer to it on `msg.embeds`? Attachments only takes a string or an array of strings.

**Comment by Slyke** [comment]
If putting the buffer directly on `msg.attachments` it errors saying that `msg.attachments` must be a string. If I `toString()` the buffer I get the following error:
![image](https://user-images.githubusercontent.com/6442613/191395372-cfc67bc3-7c38-48ee-9060-562636c6e1f4.png)

**Comment by Slyke** [comment]
I couldn't figure it out with a buffer. Not sure it's doable. I got it working using a temporary file:

```
const nodeFetch = context.global.get('nodeFetch');
const fs = context.global.get('fs');
const url = 'http://some/url/with/a.jpg';

// Random number to help avoid filename collisions (even if they are unlikely)
const getRandomIntInclusive = (min, max) => {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1) + min);
};

const pictureFilename = `${new Date().getTime()}_${getRandomIntInclusive(0, 9999).toString().padStart(4, 0)}.jpg`;
const savePath = "/tmp/"; // I run NodeRed inside Kubernetes and the tmp directory is cleared on each reboot.
const fullPath = `${savePath}${pictureFilename}`;

const res = await nodeFetch(url);
const fileStream = fs.createWriteStream(`${savePath}${pictureFilename}`);

await new Promise((resolve, reject) => { // From buffer to file
  res.body.pipe(fileStream);
  res.body.on("error", reject); // No error handling in this example
  fileStream.on("finish", resolve);
});

msg.payload =`Temporary File: '${savePath}${pictureFilename}'`;

msg.attachments = fullPath;

setTimeout(() => { // This can also be achieved without a timeout if executed after Discord has sent the message.
    fs.unlink(fullPath, () => {}); // Delete the file after 3 seconds
}, 3000);

return msg;
```

**Comment by not7cd** [comment]
Here
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/blob/d32e89727a44206437b6d85404811354a5b329fa/discord/discordMessageManager.js#L198-L203

You have the possibility to put attachments twice through `new MessageAttachment()` which can have more arguments. The resulting object looks like this:
```
MessageAttachment {
  attachment: MessageAttachment {
    attachment: 'https://example.com/original_name.png',
    name: 'other_name.png'
  },
  name: null
}
```

**Comment by Slyke** [comment]
But does that work with file buffers?

**Comment by not7cd** [comment]
Yes, I was just able to get it working with buffs. I'm getting it from an other block. I'm utterly confused how `AttachmentBuilder` and `MessageAttachment` differ. 

```javascript
console.log(Buffer.isBuffer(msg.payload.image));
let file = new discordjs.AttachmentBuilder(msg.payload.image);
file.name = "cam-1.jpg";

let newMessage = {}; 
newMessage.channel = msg.payload.channelId;
newMessage.payload = {
    "content": "",
    "tts": false,
    "embeds": [
        {
            "type": "rich",
            "title": `Vortex of Doom`,
            "description": `Tutaj będą zdjęcia`,
            "image": {
                "url": 'attachment://cam-1.jpg',
            },
        }
    ],
    "attachments": [file]
}
return newMessage;
```

**Comment by Slyke** [comment]
Awesome! Will test it out once it's merged.

**Comment by javis86** [comment]
This approach is using a function node with a reference to the latest version of discord.js, right? Could you post a json flow of this case?

**Comment by not7cd** [comment]
@javis86, this awaits merge of my PR request. You are free to patch it yourself

**Comment by javis86** [comment]
I tested on a node-red instance and It failed. I have already installed discord.js 13.8 for functions nodes, and this version does not have Attachment builder. i going to test the actual functionality, for backward compatibility and then i will merge it
We need to migrate to discord.js version 14 for full support of these feature

**Comment by javis86** [comment]
I'm moving discord.js version to 14.7 on #64, I added the possibility of work with buffers, like this:
```js
msg.embed = {
    "title": `Toyota Etios`,
      "description": `Compact Car`,
      "color": 0x00FFFF,
      "fields": [
        {
          "name": `Type`,
          "value": `Hatch`
        }
      ],
      "image": {
        "url": "attachment://etios2.jpg"
      }
};
msg.attachments = { buffer: msg.payload, name: "etios2.jpg"};

return msg;
```
