### ISSUE TITLE
Fetch Error: self signed certificate

### ISSUE THREAD

**Issue by Slyke** [Markoudstaal/node-red-contrib-discord-advanced#59]
Hello, getting this error when attempting to send a message:

![image](https://user-images.githubusercontent.com/6442613/202935925-1a25fa10-802d-4ef1-97b0-0687ed5638f8.png)

This error happens when deployed. If I attempt to send a message nothing happens. This happened with a new discord Node.

All my current nodes are erroring with:
![image](https://user-images.githubusercontent.com/6442613/202968159-98183a10-ec85-44c2-aaf0-bb4964d35ab7.png)

And I believe it's because the client is failing to send due to the FetchError and destroying itself.

I've set `NODE_TLS_REJECT_UNAUTHORIZED=0` in the environment variables, but it doesn't seem to help.

I'm using:

- NodeRed Docker: v2.2.3-16
- Node: v16.13.1

**Comment by javis86** [comment]
Not related to the node
