### ISSUE TITLE
Error when trying to deploy nodes

### ISSUE THREAD

**Issue by TristanMW** [Markoudstaal/node-red-contrib-discord-advanced#65]
Hi, when I try and deploy the nodes I get an error stating that its missing the node type
<img width="602" alt="image" src="https://user-images.githubusercontent.com/33277505/219867316-f2a57569-cc5a-47ca-aab4-97a8a97209ff.png">

When checking the Palette I see this error
<img width="701" alt="image" src="https://user-images.githubusercontent.com/33277505/219867352-cbd6d500-cd98-4906-9168-4e06f59383f0.png">

Please help

**Comment by javis86** [comment]
@TristanMW was using a older version of NodeRed (1.3)
