### ISSUE TITLE
reading FLAGS of undefined

### ISSUE THREAD

**Issue by geekgarage** [Markoudstaal/node-red-contrib-discord-advanced#70]
![image](https://user-images.githubusercontent.com/12700648/221444465-e876977e-74f0-4b4c-971f-d7d6221b738f.png)

I'm not 100% sure but i think, looking at the documentation for discord.js that "Intent" should be "GatewayIntentBits" in this file, but i'm not sure so I'm doing a bug report instead of PR
https://github.com/Markoudstaal/node-red-contrib-discord-advanced/blob/main/discord/discordMessage.js

**Comment by geekgarage** [comment]
https://discordjs.guide/popular-topics/intents.html#privileged-intents

**Comment by geekgarage** [comment]
seems like discord pushed some broken update yesterday for their API
https://status.tickettool.xyz/incidents/v5lvlrkfsmdv

**Comment by javis86** [comment]
> ![image](https://user-images.githubusercontent.com/12700648/221444465-e876977e-74f0-4b4c-971f-d7d6221b738f.png)
> 
> I'm not 100% sure but i think, looking at the documentation for discord.js that "Intent" should be "GatewayIntentBits" in this file, but i'm not sure so I'm doing a bug report instead of PR https://github.com/Markoudstaal/node-red-contrib-discord-advanced/blob/main/discord/discordMessage.js

Maybe you installed a new specific version of discord.js from console or you are using a function node with a discord.js reference. The current version of the node-red-contrib-discord-advanced use a discord.js version does not have GatewayIntentBits. 
I updated the discord.js version to 14.7.1 in alpha version.
#64

**Comment by javis86** [comment]
@geekgarage Try now with the last version of the node

**Comment by geekgarage** [comment]
Works as it should THANK YOU
