### ISSUE TITLE
cant access my flow

### ISSUE THREAD

**Issue by Minty2vr** [Markoudstaal/node-red-contrib-discord-advanced#82]
![image_2023-05-14_135147533](https://github.com/Markoudstaal/node-red-contrib-discord-advanced/assets/133433123/942b3c1c-22a8-4872-ac9b-324bd304bcb5)

i dont know any of what this means I just know the link for editing nodes wont work

**Comment by razaar** [comment]
This seems to happen if the permissions are not set correctly in the bot panel

**Comment by Minty2vr** [comment]
what permissions do i need to turn on

**Comment by Minty2vr** [comment]
i fixed it!
